//
// Created by carlosad on 4/12/24.
//

#ifndef GPUCKKS_BOOTSTRAP_CUH
#define GPUCKKS_BOOTSTRAP_CUH

#include "forwardDefs.cuh"
#include "pke/openfhe.h"

namespace FIDESlib::CKKS {
void BootstrapCPUraise(Ciphertext& ctxt,
  const int slots,
  std::shared_ptr<lbcrypto::CryptoContextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<expdtype>>>>>& CPUcc,
  lbcrypto::KeyPair<lbcrypto::DCRTPoly> keys,
  const bool prescaled);
// void Bootstrap(Ciphertext& ctxt, const int slots, const bool prescaled = false);
void Bootstrap(Ciphertext& ctxt, const int slots, const bool prescaled = false);

/**
 * @brief StC-first CKKS bootstrap: runs SlotsToCoeffs BEFORE the modulus
 *        raise, instead of after (as the standard Bootstrap() above does).
 *        Mirrors OpenFHE's FHECKKSRNS::EvalBootstrapStCFirst (introduced in
 *        OpenFHE for the "BTSlotsEncoding" bootstrap variant).
 *
 * REQUIRES the bootstrap precomputation for `slots` (cc.GetBootPrecomputation)
 * to have been generated by calling, on the CPU side,
 * cc->EvalBootstrapSetup(..., /*BTSlotsEncoding=*\/true) before LoadContext —
 * the StC/CtS matrices and levels (lEnc/lDec) it produces differ from the
 * ModRaise-first variant, and this function assumes StC-first-shaped
 * precomputation.
 *
 * REQUIRES the input ciphertext to have MORE remaining levels than the
 * ModRaise-first Bootstrap() needs, because the SlotsToCoeffs linear
 * transform is applied before ModRaise consumes any levels, instead of
 * after — see CKKS_BOOTSTRAPPING.md in OpenFHE for the q' > q level
 * accounting this implies.
 */
void BootstrapStCFirst(Ciphertext& ctxt, const int slots, const bool prescaled = false);

/**
 * @brief Same pipeline as BootstrapStCFirst, but instead of returning the
 *        ciphertext right after the standard EvalMod + double-angle +
 *        corFactor scaling, applies an extra fixed degree-26 cosine
 *        Chebyshev polynomial ("coscoeffs") followed by 2 custom
 *        double-angle iterations (4x - 4x^2, extending the period from
 *        [-4*pi, 4*pi] to [-16*pi, 16*pi], matching K=16 of sparse
 *        encapsulated secrets) as an extra precision-correction step.
 *
 * Same preconditions as BootstrapStCFirst (StC-first precomputation via
 * EvalBootstrapSetup(..., BTSlotsEncoding=true), and extra input-level
 * headroom for the initial SlotsToCoeffs pass).
 */
void BootstrapStCFirstBits(Ciphertext& ctxt, const int slots, const bool prescaled = false);

double GetPreScaleFactor(Context& cc, int slots);
void ModRaise(Ciphertext& ctxt, const int slots, const uint32_t correction, const bool prescaled = false, bool sparse_encaps = false);
} // namespace FIDESlib::CKKS

#endif // GPUCKKS_BOOTSTRAP_CUH
